### ISSUE TITLE
Set not creating

### ISSUE THREAD

**Issue by racashmoney** [zachleigh/laravel-property-bag#2]
Edit nvm. Took me a while to understand set() doesn't create if it is the default value. 

Although the json_encode is ugly if we're not using json in our db

**Comment by zachleigh** [comment]
Hello rcashmoney. Yes, if it is the default value, it will not be set in the db. This way, the database isnt filled with pointless entries. I should probably make that clearer in the code/documentation.   

About the json_encode... What exactly do you mean?

**Comment by racashmoney** [comment]
My db doesn't support json, so I looked at your original issue, and edited the migration so it supports varchar instead. However when I added something to the db, the value looked like this
 `"[\"1\"]"` (the quotes are part of it)
This was ugly and looked wrong. I looked through the package and found the json_encode functions. I removed those and just put the regular value variable there, and then it became this
`"1"` (the quotes are part of it)
So the json_encode is making things ugly in the db, plus it's extra unnecessary code since I'm not using json in my db.

**Comment by zachleigh** [comment]
The reason why it saves as json is because the `value` column contains mixed data types. In a normal db column, you would specify the data type (boolean, string, integer etc) when you create the column and then when you retrieve the entry from the db, it would be the same data type. For example, if you saved a boolean, true, it would save as 1, which is interpreted as true. False would save as 0. However, if you save true in a text field, it saves as the string 'true' and false saves as the string 'false'. Both of these strings are interpreted as true because they contain a value. This is a huge problem.    

In your case, if you're trying to save the integer 1, when you remove the json_encode functions, you're actually saving the string '1', which could become problematic. So yes, the json_encode makes the db a little ugly, but there is no other way to ensure types remain the same in a text field.

**Comment by racashmoney** [comment]
I see. I also realized not to remove the json_encode because then get() will return null.
